### ISSUE TITLE
One page layout #feature-request

### ISSUE THREAD

**Issue by grandmaster78** [agavish/itrek2017#1]
Adam, thanks for getting the site up

It would be awesome if you can show the details of the company challenges on https://itrek2017.herokuapp.com/challenges

instead of going to each link 
https://itrek2017.herokuapp.com/companies/5
https://itrek2017.herokuapp.com/companies/6

This will save us 18 clicks and a lot of time. 
# UX

**Comment by grandmaster78** [comment]
including company link and additional details

**Comment by agavish** [comment]
Fixed

**Comment by grandmaster78** [comment]
you are the best
